In [1]:
import pandas as pd
from mod06_deanonymize import load_data, link_records, deanonymization_rate

In [2]:
anon_path = "mod06_data/anonymized.csv"
aux_path = "mod06_data/auxiliary.csv"

### Load and review the data

In [3]:
anon, aux = load_data(anon_path, aux_path)

In [4]:
anon.head(20)

   anon_id  age  zip3 gender
0    ERM5C   50   432      F
1    OFJJP   75   323      F
2    I3H24   44   323      M
3    3WUYW   66   323      M
4    ZN91P   18   323      M
5    7BLKV   36   606      F
6    4SJFH   70   890      M
7    0NO3L   31   110      M
8    U060Z   80   191      F
9    1761H   58   606      M
10   I9UI2   53   432      M
11   OO0ZT   47   941      F
12   BPEI7   19   112      M
13   ULMOZ   47   110      M
14   ES0E7   75   323      F
15   XCR1D   73   606      M
16   AY6JA   69   323      M
17   Q1J6V   40   941      F
18   BU6DU   54    62      F
19   LL1K7   69    21      M

In [5]:
aux.head(20)

               name  age  zip3 gender
0       Grace Lopez   50   432      F
1    Grace Martinez   75   323      F
2      Thomas Moore   44   323      M
3       Paul Martin   66   323      M
4     Kyle Martinez   18   323      M
5       Emma Garcia   36   606      F
6        Kyle Smith   70   890      M
7      Marcus Lopez   31   110      M
8       Sally Davis   80   191      F
9     Frank Jackson   58   606      M
10          Bob Lee   53   432      M
11   Viola Williams   47   941      F
12   Roger Williams   19   112      M
13      David Davis   47   110      M
14       Emma Jones   75   323      F
15      Paul Martin   73   606      M
16     Ivan Jackson   69   323      M
17     Marcus Jones   40   941      F
18  Sally Rodriguez   54    62      F
19     Omar Jackson   69    21      M

### Merge the datasets by age, gender, and zip3 and return the unique matches

In [6]:
matches = link_records(anon, aux)
matches.head()

   anon_id           name
0    ERM5C    Grace Lopez
7    ZN91P  Kyle Martinez
14   0NO3L   Marcus Lopez
15   U060Z    Sally Davis
16   1761H  Frank Jackson

### Calculate the match rate

In [7]:
rate = deanonymization_rate(matches, anon)
print(rate)

0.421

# Discussion Questions

### Describe your reaction to the match rate. What sources of data might be prone to privacy issues?

I was surprised at how high the match rate was, and I think it just goes to show how powerful the data collected about most of us can be if it was lost to the wrong hands. It actually made me think about a YouTube video I watched recently, where an investigative journalist confirmed the real identity of a Russian spy who had fled her deep-cover mission in Naples, Italy in part by tracking the microchip number of a cat back to Russia. Data like medical and birth records would obviously be extremely prone to privacy issues, but something as simple as home ownership data or even Amazon shopping would all be prone to privacy issues as well.

### Provide examples of at least two other variables that could increase the match rate if included.

State of residence, ZIP code, and date of birth would all be examples of variables that could increase the match rate if included.